ALTER TABLE "account"
  ADD COLUMN IF NOT EXISTS "account_suffix" TEXT,
  ADD COLUMN IF NOT EXISTS "securities_account" TEXT,
  ADD COLUMN IF NOT EXISTS "initial_deposit" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "current_assets" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "default_subscription_method" TEXT;

ALTER TABLE "account_ipo"
  ADD COLUMN IF NOT EXISTS "subscription_method" TEXT,
  ADD COLUMN IF NOT EXISTS "subscription_date" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "remarks" TEXT,
  ADD COLUMN IF NOT EXISTS "allotted_shares" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "allotted_lots" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sell_plan" TEXT,
  ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
